---
- name: Configure the Timezone
  hosts: all
  vars:
    timezone: Asia/Manila
  tasks:

    - name: Update Timezone to Asia/Manila
      copy: content="{{timezone}}\n" dest=/etc/timezone owner=root group=root mode=0644
      become: true
      register: timezone

    - name: Reconfigure Timezone Data
      shell: dpkg-reconfigure -f noninteractive tzdata
      become: true
      when: timezone.changed